

CREATE TABLE IF NOT EXISTS `route` (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(255) NOT NULL,
    head TINYINT NULL DEFAULT FALSE
);


CREATE TABLE IF NOT EXISTS `location` (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NULL,
    x LONG NULL,
    y LONG NULL,
    head TINYINT NULL DEFAULT FALSE,
    route_id INT UNSIGNED DEFAULT 1,
    FOREIGN KEY (route_id)
    REFERENCES `route`(id)
    ON UPDATE SET NULL
    ON DELETE SET NULL
);

